papiNet API 1.3.0 is ready ;-) | Feature/availability
papinet/papiNet-API pull request #44
Opened 2022-06-01 11:25 UTC by patricekrakow

Adding the Availability use case.

2022-07-14 15:27 UTC, MrNordenberg requested changes
This is a MAJOR not backward compatible change, since an implemented API would need to be changed due to that quite a few properties now are required, e.g. "href" in PaginationLinks first, prev and next, further the rows 1270-1274.

Hence the version should be papiNet API 2.0.0 in accordance with the semantic versioning MAJOR.MINOR.PATCH. Study the summary of semantic versioning presented at semver.org.

2022-07-15 21:11 UTC, globaltopmedia requested changes
Some small stuff,  plus the major version discussion.

2022-07-19 10:39 UTC, larsolofsson commented
Please review and resolve 7 issues, #49 to #55

2022-07-19 11:00 UTC, larsolofsson requested changes
Please review and resolve 7 issues, https://github.com/papinet/papiNet-API/issues/49 to https://github.com/papinet/papiNet-API/issues/55

2022-07-27 10:02 UTC, patricekrakow commented on 1.3.0/mock/upload.cmd
> +cmd /c gcloud compute ssh elfralalo@node-01 --command="mkdir /home/elfralalo/papinet-mock-service-1-2-0"
Indeed. I should use a "USER" variable in that script.

2022-10-16 18:33 UTC, larsolofsson commented
**format: uuid** is missing for property **id** in GetLocationByID:

2022-12-21 15:06 UTC, merged